language: csharp

# solution: build.sln

sudo: true 

# Blacklist
branches:
  except:
    - gh-pages

# Environment variables
env:
  global:
    - GH_REPO_NAME: QFramework
    - DOXYFILE: $TRAVIS_BUILD_DIR/docs/Doxyfile
    - GH_REPO_REF: github.com/liangxiegame/QFramework.git


# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

# Build your code e.g. by calling make
script: 
    - sh ./Tools/build.sh 
    - sh ./Tools/test.sh 
notifications:
  webhooks: https://hook.bearychat.com/=bwBLe/travis/d12e4ab6659650c0e20f6f99bd07ffea
# Generate and deploy documentation
# after_success:  doxyjen
  # - cd $TRAVIS_BUILD_DIR
  # - chmod +x Tools/generateDocumentationAndDeploy.sh
  # - ./Tools/generateDocumentationAndDeploy.sh